AWSTemplateFormatVersion: '2010-09-09'
Description: EventBridge Rule for sending Security Hub reports to HackerOne

# Inputs:
  # Username
  # Password
  # CustomSecurityHubAction

Globals:
  Function:
    Timeout: 3

Resources:
  # HackerOneAPIToken
  # Type: SecretsManagerSecret
  HackerOneConnection:
    Type: AWS::Events::Connection
    Properties: 
      AuthorizationType: BASIC
      AuthParameters:
        BasicAuthParameters: 
          Password: '{{resolve:secretsmanager:HackerOneAPIToken.Arn}}'
          Username: Username.Input
      Description: Auth connection for HackerOne API
      Name: HackerOneConnection
  HackerOneApiDestination:
    Type: AWS::Events::ApiDestination
    Properties: 
      ConnectionArn: !Ref HackerOneConnection.Arn
      Description: HackerOne API Destination
      HttpMethod: POST
      InvocationEndpoint: https://api.hackerone.com/v1/reports
      InvocationRateLimitPerSecond: 100
      Name: HackerOneApiDestination
  HackerOneRule:
    Type: AWS::Events::Rule
    Properties:
      Description: A rule to send events to HackerOne
      EventPattern: 
        source: 
          - aws.securityhub
        detail-type: 
          - Security Hub Findings - Custom Action
        resources:
          - CustomSecurityHubAction.Arn
      Name: HackerOneRule
      State: ENABLED
      Targets:
       - 
         Arn: 
           Fn::GetAtt:
             - "HackerOneApiDestination"
             - "Arn"
         Id: "idmyeventrule"
         RetryPolicy:
           MaximumRetryAttempts: 4
           MaximumEventAgeInSeconds: 400
